name: WakaTime Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Data
    runs-on: ubuntu-latest
    
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
      - uses: actions/checkout@v2
      - name: Update Readme with WakaTime Data
        uses: anmol098/waka-readme-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
